# Generated by Django 5.2.6 on 2025-10-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimiento de caja', 'verbose_name_plural': 'Movimientos de caja'},
        ),
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
    ]
