# Generated by Django 5.2.6 on 2025-10-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre completo / Empresa')),
                ('customer_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Empresarial'), ('delivery', 'Delivery')], default='personal', max_length=20, verbose_name='Tipo de cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de contacto (si aplica)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Límite de crédito')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
