# Generated by Django 5.2.6 on 2025-10-08 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de servicio',
                'verbose_name_plural': 'Categorías de servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_type', models.CharField(choices=[('prenda', 'Por prenda'), ('libra', 'Por libra'), ('kilo', 'Por kilo'), ('servicio', 'Por servicio completo')], default='prenda', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time_minutes', models.PositiveIntegerField(default=30)),
                ('is_express_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.servicecategory')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('unit_of_measure', models.CharField(default='ml', max_length=20)),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Insumo de servicio',
                'verbose_name_plural': 'Insumos de servicio',
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('personal', 'Cliente personal'), ('empresa', 'Cliente empresarial'), ('vip', 'Cliente VIP')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Precio por tipo de cliente',
                'verbose_name_plural': 'Precios por tipo de cliente',
                'unique_together': {('service', 'customer_type')},
            },
        ),
    ]
