# Generated by Django 5.2.6 on 2025-10-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicematerial',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_services', to='inventory.inventoryitem', verbose_name='Insumo vinculado'),
        ),
        migrations.AddField(
            model_name='servicematerial',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='catalog.service'),
        ),
        migrations.AlterUniqueTogether(
            name='servicematerial',
            unique_together={('service', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='servicepricing',
            unique_together={('service', 'customer_type')},
        ),
    ]
