# Generated by Django 5.2.6 on 2025-10-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicematerial',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_used_in', to='inventory.inventoryitem', verbose_name='Insumo vinculado'),
        ),
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, help_text='Cantidad de insumo por unidad de servicio', max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_used_in', to='inventory.inventoryitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Componente del servicio',
                'verbose_name_plural': 'Componentes del servicio',
                'unique_together': {('service', 'item')},
            },
        ),
    ]
