# Generated by Django 5.2.6 on 2025-10-11 12:50

import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trezo', help_text='Nombre que aparece en el título, preloader y footer.', max_length=100, verbose_name='Nombre del sistema')),
                ('tagline', models.CharField(blank=True, max_length=150, null=True, verbose_name='Eslogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=theme.models.upload_logo_path, verbose_name='Logo principal')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=theme.models.upload_favicon_path, verbose_name='Favicon')),
                ('preloader_text', models.CharField(default='TREZO', max_length=50, verbose_name='Texto del preloader')),
                ('footer_text', models.CharField(default='© Trezo - 2025', max_length=200, verbose_name='Texto del footer')),
                ('is_active', models.BooleanField(default=False, help_text='Solo puede haber un tema activo.', verbose_name='¿Tema activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema visual',
                'verbose_name_plural': 'Temas visuales',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
