# Generated by Django 5.2.6 on 2025-10-11 13:01

import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={},
        ),
        migrations.AlterField(
            model_name='theme',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=theme.models.upload_favicon_path),
        ),
        migrations.AlterField(
            model_name='theme',
            name='footer_text',
            field=models.CharField(default='© Trezo - 2025', max_length=200),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=theme.models.upload_logo_path),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='Trezo', max_length=100, verbose_name='Nombre del sistema'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='preloader_text',
            field=models.CharField(default='TREZO', max_length=50),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tagline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
